name: Remote SSH Command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Create remote project directory
        uses: appleboy/ssh-action@v1
        with:
          host: 138.199.169.12
          username: root
          key: ${{ secrets.SECRET }}
          script: |
            mkdir ~/app
            ls -al

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Copy project files to remote project directory
        uses: appleboy/scp-action@v1
        with:
            host: 138.199.169.12
            username: root
            key: ${{ secrets.SECRET }}
            source: .
            target: "~/app"

      - name: Build image and run container
        uses: appleboy/ssh-action@v1
        with:
          host: 138.199.169.12
          username: root
          key: ${{ secrets.SECRET }}
          script: |
            cd ~/app
            docker rmi tuto-docker:latest --force || true
            docker build -t tuto-docker:latest .
            docker run -d -p 5173:3000 tuto-docker:latest